export const DEMOS = [
  {
    id: "text-basics",
    title: "Text Basics",
    screen: "Text Basics",
    kind: "Go layout",
    summary: "Labels, wrapping paragraphs, and padded panels to show simple text composition.",
    tags: ["code-first", "text", "panels"],
    sources: [{ label: "text_basics.go", path: "examples/zoo/screens/text_basics.go", lang: "go" }],
  },
  {
    id: "stacks",
    title: "Stacks",
    screen: "Stacks",
    kind: "Go layout",
    summary: "Weighted spacers in an HStack to demonstrate justify and spacing controls.",
    tags: ["stack", "spacing"],
    sources: [{ label: "stacks.go", path: "examples/zoo/screens/stacks.go", lang: "go" }],
  },
  {
    id: "alignment",
    title: "Alignment",
    screen: "Alignment",
    kind: "Go layout",
    summary: "Side-by-side text alignment samples inside a constrained grid.",
    tags: ["alignment", "grid"],
    sources: [{ label: "alignment.go", path: "examples/zoo/screens/alignment.go", lang: "go" }],
  },
  {
    id: "nesting",
    title: "Nesting",
    screen: "Nesting",
    kind: "Go layout",
    summary: "Three levels of padded panels to highlight nested layouts and inherited fill.",
    tags: ["nesting", "panels"],
    sources: [{ label: "nesting.go", path: "examples/zoo/screens/nesting.go", lang: "go" }],
  },
  {
    id: "dirty",
    title: "Dirty",
    screen: "Dirty",
    kind: "Go layout",
    summary: "Dirty flag in action: toggles label text every second to invalidate cache.",
    tags: ["dirty", "state"],
    sources: [{ label: "dirty.go", path: "examples/zoo/screens/dirty.go", lang: "go" }],
  },
  {
    id: "visibility-fx",
    title: "Visibility FX",
    screen: "Visibility FX",
    kind: "XML / CSS",
    summary: "XML-driven cards that animate visibility on a timer with scroll preview.",
    tags: ["xml", "visibility", "scroll"],
    sources: [
      { label: "visibility_demo.xml", path: "examples/zoo/screens/layouts/visibility_demo.xml", lang: "xml" },
      { label: "visibility_demo.css", path: "examples/zoo/screens/layouts/visibility_demo.css", lang: "css" },
      { label: "visibility_demo.go", path: "examples/zoo/screens/visibility_demo.go", lang: "go", focus: "buildVisibilityDemo" },
    ],
  },
  {
    id: "images",
    title: "Images",
    screen: "Images",
    kind: "Go layout",
    summary: "Nine-slice panels, SVG rasterization, and fit modes for responsive art.",
    tags: ["images", "nine-slice", "responsive"],
    sources: [{ label: "images.go", path: "examples/zoo/screens/images.go", lang: "go" }],
  },
  {
    id: "tinted-surfaces",
    title: "Tinted Surfaces",
    screen: "Tinted Surfaces",
    kind: "Go layout",
    summary: "Demonstrates tint-color on panels and images plus masked icon recoloring.",
    tags: ["tint", "panels", "images"],
    sources: [{ label: "tint_demo.go", path: "examples/zoo/screens/tint_demo.go", lang: "go", focus: "buildTintDemo" }],
  },
  {
    id: "assets",
    title: "Assets",
    screen: "Assets",
    kind: "Go layout",
    summary: "Scrollable asset gallery using FlowStack and image loader helpers.",
    tags: ["gallery", "scroll", "assets"],
    sources: [{ label: "assets_gallery.go", path: "examples/zoo/screens/assets_gallery.go", lang: "go" }],
  },
  {
    id: "justify",
    title: "Justify",
    screen: "Justify",
    kind: "Go layout",
    summary: "Justify modes shown across multiple rows with consistent card styling.",
    tags: ["justify", "hstack"],
    sources: [{ label: "justify_gallery.go", path: "examples/zoo/screens/justify_gallery.go", lang: "go" }],
  },
  {
    id: "spacing-align",
    title: "Spacing & Align",
    screen: "Spacing/Align",
    kind: "Go layout",
    summary: "Spacing and cross-axis alignment tweaks visualized with labeled cards.",
    tags: ["spacing", "alignment"],
    sources: [{ label: "spacing_align.go", path: "examples/zoo/screens/spacing_align.go", lang: "go" }],
  },
  {
    id: "wrap",
    title: "Wrap",
    screen: "Wrap",
    kind: "Go layout",
    summary: "FlowStack wraps chips across lines while honoring spacing and alignment.",
    tags: ["flowstack", "wrap"],
    sources: [{ label: "wrap_gallery.go", path: "examples/zoo/screens/wrap_gallery.go", lang: "go" }],
  },
  {
    id: "grid",
    title: "Grid",
    screen: "Grid",
    kind: "Go layout",
    summary: "Grid component with min/max cell widths and flowing cards.",
    tags: ["grid", "responsive"],
    sources: [{ label: "grid.go", path: "examples/zoo/screens/grid.go", lang: "go" }],
  },
  {
    id: "grid-align",
    title: "Grid Align",
    screen: "Grid Align",
    kind: "Go layout",
    summary: "Grid alignment variations, demonstrating justify/align combinations.",
    tags: ["grid", "alignment"],
    sources: [{ label: "grid_align.go", path: "examples/zoo/screens/grid_align.go", lang: "go" }],
  },
  {
    id: "row-align",
    title: "Row Align",
    screen: "Row Align",
    kind: "Go layout",
    summary: "Row alignment gallery for cross-axis positioning within stacks.",
    tags: ["rows", "alignment"],
    sources: [{ label: "row_align.go", path: "examples/zoo/screens/row_align.go", lang: "go" }],
  },
  {
    id: "rounded-corners",
    title: "Rounded Corners",
    screen: "Rounded Corners",
    kind: "Go layout",
    summary: "Rounded panels, per-corner radii, and bordered hero cards.",
    tags: ["corners", "panels"],
    sources: [{ label: "radius_demo.go", path: "examples/zoo/screens/radius_demo.go", lang: "go", focus: "buildRadiusShowcase" }],
  },
  {
    id: "positioning",
    title: "Positioning",
    screen: "Positioning",
    kind: "XML / CSS",
    summary: "CSS-like position offsets, overlays, and fixed badges driven from XML.",
    tags: ["position", "xml"],
    sources: [
      { label: "positioning_demo.xml", path: "examples/zoo/screens/layouts/positioning_demo.xml", lang: "xml" },
      { label: "positioning_demo.css", path: "examples/zoo/screens/layouts/positioning_demo.css", lang: "css" },
      { label: "positioning_demo.go", path: "examples/zoo/screens/positioning_demo.go", lang: "go", focus: "buildPositioningDemo" },
    ],
  },
  {
    id: "viewport-column",
    title: "Viewport Column",
    screen: "Viewport Column",
    kind: "Go layout",
    summary: "Sticky middle column with scrollable feed built purely in Go.",
    tags: ["scroll", "columns"],
    sources: [{ label: "middle_column.go", path: "examples/zoo/screens/middle_column.go", lang: "go", focus: "buildViewportColumn" }],
  },
  {
    id: "viewport-column-xml",
    title: "Viewport Column (XML)",
    screen: "Viewport Column (XML)",
    kind: "XML / CSS",
    summary: "XML version of the sticky column demo using shared styles.",
    tags: ["xml", "scroll"],
    sources: [
      { label: "viewport_column.xml", path: "examples/zoo/screens/layouts/viewport_column.xml", lang: "xml" },
      { label: "viewport_column.css", path: "examples/zoo/screens/layouts/viewport_column.css", lang: "css" },
      { label: "viewport_column_xml.go", path: "examples/zoo/screens/viewport_column_xml.go", lang: "go" },
    ],
  },
  {
    id: "outlines",
    title: "Outlines",
    screen: "Outlines",
    kind: "Go layout",
    summary: "Overlay outlines to visualize component frames and padding.",
    tags: ["debug", "outlines"],
    sources: [{ label: "outlines.go", path: "examples/zoo/screens/outlines.go", lang: "go" }],
  },
  {
    id: "xml-demo",
    title: "XML Demo",
    screen: "XML Demo",
    kind: "XML / CSS",
    summary: "General-purpose XML layout with custom elements and particle field.",
    tags: ["xml", "custom elements"],
    sources: [
      { label: "demo.xml", path: "examples/zoo/screens/layouts/demo.xml", lang: "xml" },
      { label: "demo.css", path: "examples/zoo/screens/layouts/demo.css", lang: "css" },
      { label: "base.css", path: "examples/zoo/screens/layouts/base.css", lang: "css" },
      { label: "xml_demo.go", path: "examples/zoo/screens/xml_demo.go", lang: "go", focus: "buildXMLDemo" },
    ],
  },
  {
    id: "assets-xml",
    title: "Assets XML",
    screen: "Assets XML",
    kind: "XML / CSS",
    summary: "XML version of the asset gallery using shared theme styles.",
    tags: ["xml", "gallery"],
    sources: [
      { label: "assets_demo.xml", path: "examples/zoo/screens/layouts/assets_demo.xml", lang: "xml" },
      { label: "demo.css", path: "examples/zoo/screens/layouts/demo.css", lang: "css" },
      { label: "base.css", path: "examples/zoo/screens/layouts/base.css", lang: "css" },
      { label: "xml_demo.go", path: "examples/zoo/screens/xml_demo.go", lang: "go", focus: "buildXMLAssetsDemo" },
    ],
  },
  {
    id: "auto-font-xml",
    title: "Auto Font XML",
    screen: "Auto Font XML",
    kind: "XML / CSS",
    summary: "Auto font sizing and font families declared in XML + CSS.",
    tags: ["xml", "text"],
    sources: [
      { label: "font_auto.xml", path: "examples/zoo/screens/layouts/font_auto.xml", lang: "xml" },
      { label: "font_auto.css", path: "examples/zoo/screens/layouts/font_auto.css", lang: "css" },
      { label: "xml_demo.go", path: "examples/zoo/screens/xml_demo.go", lang: "go", focus: "buildXMLAutoFontDemo" },
    ],
  },
  {
    id: "rounded-xml",
    title: "Rounded XML",
    screen: "Rounded XML",
    kind: "XML / CSS",
    summary: "Corner radii, borders, and fills authored in XML.",
    tags: ["xml", "corners"],
    sources: [
      { label: "radius_demo.xml", path: "examples/zoo/screens/layouts/radius_demo.xml", lang: "xml" },
      { label: "radius_demo.css", path: "examples/zoo/screens/layouts/radius_demo.css", lang: "css" },
      { label: "xml_demo.go", path: "examples/zoo/screens/xml_demo.go", lang: "go", focus: "buildXMLRadiusDemo" },
    ],
  },
  {
    id: "theme-xml",
    title: "Theme XML",
    screen: "Theme XML",
    kind: "XML / CSS",
    summary: "Light/dark theme toggle handled by CSS class switching.",
    tags: ["xml", "theme"],
    sources: [
      { label: "theme_demo.xml", path: "examples/zoo/screens/layouts/theme_demo.xml", lang: "xml" },
      { label: "theme_demo.css", path: "examples/zoo/screens/layouts/theme_demo.css", lang: "css" },
      { label: "xml_demo.go", path: "examples/zoo/screens/xml_demo.go", lang: "go", focus: "buildXMLThemeDemo" },
    ],
  },
  {
    id: "flowstack-xml",
    title: "FlowStack XML",
    screen: "FlowStack XML",
    kind: "XML / CSS",
    summary: "XML FlowStack chips with wrap, spacing, and CSS-driven colors.",
    tags: ["xml", "flowstack"],
    sources: [
      { label: "flow_stack.xml", path: "examples/zoo/screens/layouts/flow_stack.xml", lang: "xml" },
      { label: "flow_stack.css", path: "examples/zoo/screens/layouts/flow_stack.css", lang: "css" },
      { label: "base.css", path: "examples/zoo/screens/layouts/base.css", lang: "css" },
      { label: "xml_demo.go", path: "examples/zoo/screens/xml_demo.go", lang: "go", focus: "buildXMLFlowStackDemo" },
    ],
  },
  {
    id: "templates-xml",
    title: "Templates XML",
    screen: "Templates XML",
    kind: "XML / CSS",
    summary: "Template instantiation and dialog variables powering a crew roster.",
    tags: ["xml", "templates"],
    sources: [
      { label: "template_demo.xml", path: "examples/zoo/screens/layouts/template_demo.xml", lang: "xml" },
      { label: "template_demo.css", path: "examples/zoo/screens/layouts/template_demo.css", lang: "css" },
      { label: "template_demo.go", path: "examples/zoo/screens/template_demo.go", lang: "go", focus: "buildXMLTemplateDemo" },
    ],
  },
  {
    id: "scoreboard-xml",
    title: "Scoreboard XML",
    screen: "Scoreboard XML",
    kind: "XML / CSS",
    summary: "Live-updating scoreboard view using template instances and dialog variables.",
    tags: ["xml", "data binding"],
    sources: [
      { label: "scoreboard_demo.xml", path: "examples/zoo/screens/layouts/scoreboard_demo.xml", lang: "xml" },
      { label: "scoreboard_demo.css", path: "examples/zoo/screens/layouts/scoreboard_demo.css", lang: "css" },
      { label: "scoreboard_demo.go", path: "examples/zoo/screens/scoreboard_demo.go", lang: "go", focus: "buildXMLScoreboardDemo" },
    ],
  },
  {
    id: "align-self-xml",
    title: "align-self XML",
    screen: "align-self XML",
    kind: "XML / CSS",
    summary: "Align-self modifiers applied inside stacks for cross-axis overrides.",
    tags: ["xml", "alignment"],
    sources: [
      { label: "align_self.xml", path: "examples/zoo/screens/layouts/align_self.xml", lang: "xml" },
      { label: "align_self.css", path: "examples/zoo/screens/layouts/align_self.css", lang: "css" },
      { label: "base.css", path: "examples/zoo/screens/layouts/base.css", lang: "css" },
      { label: "xml_demo.go", path: "examples/zoo/screens/xml_demo.go", lang: "go", focus: "buildXMLAlignSelfDemo" },
    ],
  },
];
